name: Deploy to WordPress.org
on:
  push:
    branches:
    - "feat/diploy-automation"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run diploy-build
      - uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.WP_SVN_PASS }}
          SVN_USERNAME: ${{ secrets.WP_SVN_USER }}
          SLUG: howdywp
